# Site settings
title: Youngbin Han
email: sukso96100@gmail.com
description: "My own Jekyll based blog"
baseurl: ""
url: "http://sukso96100.github.io"

# Build settings
markdown: kramdown
permalink: pretty
