# Site settings
title: Youngbin Han
email: sukso96100@gmail.com
description: "Youngbin Han's Perssonal Jekyll Based Blog!"
baseurl: ""
url: "http://sukso96100.github.io"

# Build settings
markdown: kramdown
permalink: pretty
